on:
  push:
    tags:
      - 'v*'

name: Release

jobs:
  build:
    name: Build Linux Release
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release
      - run: strip target/release/dockfoxprox
      - run: zip --junk-paths dockfoxprox-linux.zip target/release/dockfoxprox
      - uses: actions/upload-artifact@v4
        with:
          name: dockfoxprox-linux
          path: dockfoxprox-linux.zip

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dockfoxprox-linux
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: dockfoxprox-linux.zip
